[project]
name = "minimaxh3-easy-extended"
description = "Extended MiniMax H3 workflow nodes for ComfyUI."
version = "2.0.69"
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/c-jaro/ComfyUI-MiniMaxH3-Easy-Extended"
Documentation = "https://github.com/c-jaro/ComfyUI-MiniMaxH3-Easy-Extended#readme"
"Bug Tracker" = "https://github.com/c-jaro/ComfyUI-MiniMaxH3-Easy-Extended/issues"

[tool.comfy]
PublisherId = "c-jaro"
DisplayName = "MiniMax H3 Easy Extended"
Icon = ""