// UI-only writing presets for open MiniMax H3 prompt fields.
//
// These are NOT model enums unless a caller explicitly labels them as such.
// The official fixed vocabularies (camera motion, task types, retention markers,
// stable dialogue languages) live in h3_guidelines.js. The presets here are
// ergonomic starting points for free-form natural-language fields and always
// remain editable through the editor's Custom… choice.

const choice = (label, insertText, detail = "") => Object.freeze({ label, insertText, detail });
const frozen = (items) => Object.freeze(items);

export const PROMPT_CHOICE_GROUPS = Object.freeze({
  retainedTraits: frozen([
    choice("Identity + face", "identity, facial features, and distinctive appearance", "Preserve who the subject is and the facial identity cues."),
    choice("Outfit + accessories", "clothing, accessories, and their visible details", "Preserve wardrobe and worn items."),
    choice("Body proportions", "body proportions, silhouette, and scale", "Preserve overall physical proportions."),
    choice("Structure / layout", "structure, layout, and spatial arrangement", "Preserve non-character structure or composition."),
    choice("Color + material", "colors, materials, textures, and surface finish", "Preserve surface-level visual traits."),
  ]),
  changedTraits: frozen([
    choice("Hair / grooming", "hair style, hair color, and grooming", "Allow appearance changes focused on hair/grooming."),
    choice("Clothing", "clothing, accessories, and wardrobe details", "Allow wardrobe changes."),
    choice("Color / material", "colors, materials, textures, and surface finish", "Allow surface/material changes."),
    choice("Pose / action", "pose, gesture, orientation, and action", "Allow motion/pose changes while preserving identity."),
    choice("Environment", "background, environment, props, and lighting", "Allow scene changes around a preserved subject."),
    choice("Composition", "framing, viewpoint, placement, and spatial relationships", "Allow composition changes."),
  ]),
  attributeTransfer: frozen([
    choice("Hair / grooming", "hair style, hair color, and grooming traits", "Transfer hair/grooming traits."),
    choice("Clothing / material", "clothing design, fabric, and material traits", "Transfer wardrobe/material traits."),
    choice("Accessory / prop", "accessory or prop design traits", "Transfer a visible accessory/prop design."),
    choice("Surface pattern", "surface pattern, markings, and fine-detail design", "Transfer texture/pattern/detail."),
    choice("Color palette", "color palette and color relationships", "Transfer color treatment."),
    choice("Motion / action", "action pattern, pose sequence, and timing", "Transfer movement rather than appearance."),
  ]),
  weakVisual: frozen([
    choice("Style", "visual style", "Keep only broad style similarity."),
    choice("Category", "content category", "Keep broad semantic-category similarity."),
    choice("Composition", "composition and layout", "Keep broad framing/layout similarity."),
    choice("Atmosphere", "visual atmosphere", "Keep broad atmospheric similarity."),
    choice("Color palette", "color palette", "Keep broad color similarity."),
  ]),
  audioSegments: frozen([
    choice("Opening segment", "the opening segment", "Reuse a contiguous opening portion."),
    choice("Middle segment", "a middle segment", "Reuse a contiguous middle portion."),
    choice("Ending segment", "the ending segment", "Reuse a contiguous ending portion."),
    choice("Dialogue / vocal layer", "the dialogue or vocal layer", "Copy only the vocal layer."),
    choice("Music layer", "the music layer", "Copy only music."),
    choice("Ambience / SFX layer", "the ambience and sound-effects layer", "Copy ambience/SFX without the rest of the mix."),
  ]),
  audioEdits: frozen([
    choice("Add ambience", "add newly generated ambience", "Keep copied audio and add ambience."),
    choice("Add dialogue", "add newly generated dialogue", "Keep copied audio and add target dialogue."),
    choice("Add score", "add a newly generated music layer", "Keep copied audio and add score."),
    choice("Replace dialogue", "replace the dialogue or vocal layer", "Replace speech/vocals after copying."),
    choice("Replace score", "replace the music layer", "Replace music after copying."),
    choice("Remove a layer", "remove an unwanted audio layer", "Delete one component of the copied mix."),
  ]),
  audioProperties: frozen([
    choice("Timbre", "timbre", "Reference voice/instrument tone without copying the signal."),
    choice("Delivery", "delivery and speaking cadence", "Reference how a voice is delivered."),
    choice("Rhythm", "rhythm", "Reference rhythmic behavior."),
    choice("Music style", "music style and instrumentation", "Reference score style/instrumentation."),
    choice("Dialogue / lyric content", "dialogue or lyric content", "Reference verbal content without copying the waveform."),
    choice("Sound texture", "sound texture", "Reference sonic texture."),
    choice("Atmosphere", "audio atmosphere", "Reference broad sonic atmosphere."),
  ]),
  audioCategory: frozen([
    choice("Voice", "voice character", "Broad vocal similarity."),
    choice("Music", "music category and texture", "Broad musical similarity."),
    choice("Ambience", "ambient environment", "Broad ambience similarity."),
    choice("Foley / SFX", "foley and sound-effect character", "Broad physical/SFX similarity."),
    choice("Room tone", "room tone and acoustic space", "Broad room/acoustic similarity."),
    choice("Environmental texture", "environmental sound texture", "Broad environmental sonic similarity."),
  ]),
  trackedSubject: frozen([
    // <Subject N> is MiniMax's reusable visible-content unit, not a synonym
    // for "person". Keep the inserted noun phrase natural in
    // "@SubjectN is {tracked subject} shown in ..."; the menu label carries
    // the category, so the prompt itself does not need meta wording such as
    // "the referenced person or character".
    choice("Person", "the person", "Reusable visible person."),
    choice("Character", "the character", "Reusable visible character."),
    choice("Animal", "the animal", "Reusable visible animal."),
    choice("Object / prop", "the object or prop", "Reusable object or prop."),
    choice("Scene / environment", "the scene, background, or environment", "Reusable scene/background/environment."),
    choice("Clothing / wardrobe", "the clothing or wardrobe element", "Reusable clothing or wardrobe content."),
    choice("Interface", "the visible interface", "Reusable visible interface."),
    choice("Visual effect", "the visual effect", "Reusable visual effect."),
    choice("Visual style / look", "the visual style or look", "Reusable visual style/look."),
    choice("Action / motion", "the action or motion pattern", "Reusable action, motion, or performance."),
    choice("Expression / pose", "the expression or pose", "Reusable expression or pose."),
  ]),
  actionStage: frozen([
    choice("Turn / reorient", "The subject turns and reorients toward the new focus", "A simple orientation change."),
    choice("Reach / interact", "The subject reaches toward and interacts with the object", "Hand/object interaction."),
    choice("Walk / run", "The subject moves across the scene", "Locomotion through the frame."),
    choice("Pick up / manipulate", "The subject picks up and manipulates the object", "Object handling."),
    choice("Enter / exit", "The subject enters or exits the frame", "Frame-boundary movement."),
    choice("Transform / change state", "The subject or object visibly changes state", "Visible transformation/state change."),
    choice("React", "The subject visibly reacts to the preceding event", "Reaction beat."),
  ]),
  timedActionStage: frozen([
    choice("Turn / reorient", "the subject turns and reorients toward the new focus", "Clause for a within-shot timestamp."),
    choice("Reach / interact", "the subject reaches toward and interacts with the object", "Clause for a within-shot timestamp."),
    choice("Walk / run", "the subject moves across the scene", "Clause for a within-shot timestamp."),
    choice("Pick up / manipulate", "the subject picks up and manipulates the object", "Clause for a within-shot timestamp."),
    choice("Enter / exit", "the subject enters or exits the frame", "Clause for a within-shot timestamp."),
    choice("Transform / change state", "the subject or object visibly changes state", "Clause for a within-shot timestamp."),
    choice("React", "the subject visibly reacts to the preceding event", "Clause for a within-shot timestamp."),
  ]),
  completionStage: frozen([
    choice("Settle into pose", "The movement resolves and the subject settles into the final pose", "End on a stable pose."),
    choice("Come to rest", "The moving subject or object slows and comes to rest", "Resolve physical motion."),
    choice("Release object", "The interaction completes as the subject releases the object", "Finish an object interaction."),
    choice("Exit frame", "The action completes as the subject exits the frame", "End through frame exit."),
    choice("Finish transformation", "The visible transformation completes and stabilizes", "Land on the completed changed state."),
    choice("Hold final state", "The subject reaches the intended final state and holds it", "Make the final state explicit."),
  ]),
  motionQualities: frozen([
    choice("Slow + measured", "slow, measured timing with controlled body mechanics and a smooth trajectory", "Controlled deliberate motion."),
    choice("Fast + snappy", "fast timing with crisp acceleration, clear stops, and a direct trajectory", "Fast decisive motion."),
    choice("Smooth + continuous", "smooth continuous timing with uninterrupted motion and natural follow-through", "Continuous motion."),
    choice("Weighty + physical", "weighty timing with visible inertia, balance shifts, and grounded trajectories", "Emphasize mass and body mechanics."),
    choice("Precise + mechanical", "precise repeatable timing with rigid mechanics and exact trajectories", "Mechanical/robotic motion."),
    choice("Loose + organic", "loose organic timing with asymmetry, overlap, and natural trajectory variation", "Organic natural movement."),
  ]),
  motionPerformance: frozen([
    choice("Walk / gait", "the walking gait, stride timing, weight shifts, and arm swing", "Transfer a walking performance."),
    choice("Run / sprint", "the running performance, stride cadence, torso drive, and footfall timing", "Transfer a running performance."),
    choice("Jump / landing", "the jump performance, takeoff timing, airborne body shape, and landing recovery", "Transfer a jump."),
    choice("Acrobatic move", "the acrobatic performance, pose sequence, rotation timing, and landing mechanics", "Transfer an acrobatic action."),
    choice("Dance / choreography", "the dance performance, choreography, beat timing, body isolations, and transitions", "Transfer choreography."),
    choice("Gesture / acting", "the gesture and acting performance, including posture changes, hand motion, and reaction timing", "Transfer acted body language."),
    choice("Object manipulation", "the object-manipulation performance, hand path, contact timing, grip changes, and release", "Transfer an interaction performance."),
  ]),
  motionPattern: frozen([
    choice("Walking pattern", "walking gait and stride pattern", "Reusable walking motion."),
    choice("Running pattern", "running stride and cadence pattern", "Reusable running motion."),
    choice("Jump pattern", "jump, airborne, and landing pattern", "Reusable jump motion."),
    choice("Turn / reorient pattern", "turning and reorientation pattern", "Reusable orientation change."),
    choice("Acrobatic pattern", "acrobatic pose and rotation pattern", "Reusable acrobatic motion."),
    choice("Dance pattern", "dance choreography and transition pattern", "Reusable choreography."),
    choice("Object-interaction pattern", "object-manipulation and hand-contact pattern", "Reusable manipulation motion."),
  ]),
  motionMechanics: frozen([
    choice("Full mechanics", "the ordered pose sequence, timing, weight shifts, body mechanics, and trajectory", "Follow the complete movement structure."),
    choice("Pose sequence", "the ordered pose sequence and transitions between poses", "Prioritize pose progression."),
    choice("Timing / rhythm", "the action timing, cadence, pauses, and acceleration changes", "Prioritize temporal structure."),
    choice("Weight / balance", "the weight shifts, balance changes, center-of-mass movement, and recovery", "Prioritize believable body mechanics."),
    choice("Trajectory", "the body and limb trajectories through space, including takeoff and landing paths", "Prioritize spatial paths."),
    choice("Contact mechanics", "the contact points, grip changes, impacts, recoil, and release timing", "Prioritize interactions/contact."),
    choice("Follow-through", "the overlap, inertia, follow-through, and settling after the main action", "Prioritize secondary mechanics."),
  ]),
  sourceContribution: frozen([
    choice("Identity / appearance", "identity, face, clothing, proportions, and overall appearance", "Use the source for visible identity/appearance."),
    choice("Front view", "the frontal appearance and proportions", "Use a frontal reference view."),
    choice("Side / back view", "the side or back appearance and proportions", "Use an alternate view."),
    choice("Pose / composition", "pose, framing, placement, and spatial relationships", "Use the source for composition."),
    choice("Motion / action", "action, pose sequence, timing, and body mechanics", "Use the source for motion."),
    choice("Camera movement", "camera movement and camera timing", "Use the source for camera behavior."),
    choice("Cuts / rhythm", "cut order, pacing, rhythm, and temporal structure", "Use the source for edit rhythm/structure."),
    choice("Environment", "environment, background, props, and scene layout", "Use the source for setting."),
    choice("Visual style", "visual style, lighting, color treatment, and materials", "Use the source for style."),
    choice("Close-up detail", "fine close-up detail and surface appearance", "Use the source for detail."),
  ]),
  premise: frozen([
    choice("Character action", "a character-driven action that develops continuously through the shot", "High-level subject/action premise."),
    choice("Object interaction", "a clear object interaction with a visible beginning, manipulation, and result", "High-level object-interaction premise."),
    choice("Environment change", "a visible environmental or lighting change that develops through the shot", "High-level scene-change premise."),
    choice("Motion transfer", "the referenced action or performance applied to the target subject", "High-level motion-reference premise."),
    choice("Edit source", "an edit of the referenced source video while retaining its intended temporal structure", "High-level video-edit premise."),
    choice("Continuation", "a continuation from the referenced ending state into a new action", "High-level continuation premise."),
    choice("Style-led generation", "new content generated in the referenced visual style", "High-level style-reference premise."),
  ]),
  shotProgression: frozen([
    choice("Single continuous shot", "a single continuous-shot progression from setup through action to resolution", "No cut."),
    choice("Wide → medium → close", "an establishing wide view followed by a medium action view and then a close detail", "Classic scale progression."),
    choice("Establish → action → result", "an establishing shot followed by an action-focused shot and then a result or reaction shot", "Narrative progression."),
    choice("Subject → reaction → detail", "a subject-focused shot followed by a reaction shot and then a detail insert", "Reaction/detail progression."),
    choice("Reference-matched rhythm", "the major cut and pacing progression established by the reference video", "Follow a reference edit rhythm."),
  ]),
  summaryRelationships: frozen([
    choice("Character action", "The target video follows a character-driven action that develops continuously through the shot.", "Complete summary sentence for a subject/action premise."),
    choice("Object interaction", "The target video follows a clear object interaction with a visible setup, manipulation, and result.", "Complete summary sentence for an object interaction."),
    choice("Environment change", "The target video shows a visible environmental or lighting change that develops through the shot.", "Complete summary sentence for a scene change."),
    choice("Motion transfer", "The target video applies the referenced action or performance to the target subject.", "Complete summary sentence for motion transfer."),
    choice("Edit source", "The target video edits the referenced source video while retaining its intended temporal structure.", "Complete summary sentence for video editing."),
    choice("Continuation", "The target video continues from the referenced ending state into a new action.", "Complete summary sentence for continuation."),
    choice("Style-led generation", "The target video generates new content in the referenced visual style.", "Complete summary sentence for style-led generation."),
    choice("Single continuous shot", "The target video uses one continuous shot that develops from setup through action to resolution.", "Complete summary sentence for a no-cut structure."),
    choice("Wide → medium → close", "The target video progresses from an establishing wide view to a medium action view and then a close detail.", "Complete summary sentence for scale progression."),
    choice("Establish → action → result", "The target video progresses from an establishing shot to an action-focused shot and then a result or reaction shot.", "Complete summary sentence for narrative progression."),
    choice("Subject → reaction → detail", "The target video progresses from a subject-focused shot to a reaction shot and then a detail insert.", "Complete summary sentence for reaction/detail progression."),
    choice("Reference-matched rhythm", "The target video follows the major cut and pacing progression established by the reference video.", "Complete summary sentence for reference-matched edit rhythm."),
  ]),
  visualStyle: frozen([
    choice("Cinematic", "a cinematic style", "Common style named in MiniMax's prompt guide."),
    choice("Live-action", "a live-action style", "Common style named in MiniMax's prompt guide."),
    choice("Cinematic live-action", "a cinematic live-action style", "Useful combination of two guide examples."),
    choice("2D-animated", "a 2D-animated style", "Common style named in MiniMax's prompt guide."),
    choice("3D CG", "a 3D CG style", "Common style named in MiniMax's prompt guide."),
    choice("Claymation", "a claymation style", "Common style named in MiniMax's prompt guide."),
    choice("Watercolor", "a watercolor style", "Common style named in MiniMax's prompt guide."),
    choice("Vintage film", "a vintage-film style", "Common style named in MiniMax's prompt guide."),
  ]),
  styleComposition: frozen([
    choice("Cinematic · centered", "a cinematic style with a centered primary subject and clear negative space", "Combined style + opening composition."),
    choice("Live-action · rule of thirds", "a live-action style with the primary subject placed on a rule-of-thirds line", "Combined style + opening composition."),
    choice("Cinematic live-action · layered depth", "a cinematic live-action style with clear foreground, midground, and background depth", "Combined style + opening composition."),
    choice("2D-animated · centered", "a 2D-animated style with a centered, clearly readable primary subject", "Combined style + opening composition."),
    choice("3D CG · wide", "a 3D CG style with a wide composition that keeps both subject and environment readable", "Combined style + opening composition."),
    choice("Watercolor · environmental", "a watercolor style with an environment-led opening composition", "Combined style + opening composition."),
  ]),
  styleTraits: frozen([
    choice("Soft + neutral + realistic", "soft directional lighting, neutral color grading, and realistic materials", "Natural restrained style traits."),
    choice("Warm practical light", "warm practical lighting, gentle contrast, and natural material texture", "Warm interior look."),
    choice("Cool directional light", "cool directional lighting, restrained saturation, and crisp surface detail", "Cooler graphic look."),
    choice("High contrast", "high-contrast lighting, deep shadows, and strongly separated highlights", "Harder dramatic lighting."),
    choice("Soft diffuse", "soft diffuse lighting, low contrast, and smooth material response", "Soft even look."),
    choice("Stylized material", "stylized color treatment, simplified materials, and deliberately non-photoreal surface detail", "Non-photoreal look."),
  ]),
  composition: frozen([
    choice("Centered single subject", "a centered primary subject with clear negative space around it", "Simple centered composition."),
    choice("Rule-of-thirds", "the primary subject placed on a rule-of-thirds line with the environment visible", "Off-center composition."),
    choice("Two-shot", "two subjects clearly separated within the same frame", "Two-person/subject composition."),
    choice("Layered depth", "foreground, midground, and background elements creating clear depth", "Depth-rich composition."),
    choice("Symmetrical", "a symmetrical composition with the primary subject centered on the scene axis", "Strong symmetry."),
    choice("Environmental establishing", "a wide environment-dominant composition with the subject small in frame", "Establishing composition."),
  ]),
  poseState: frozen([
    choice("Standing neutral", "the subject standing in a stable neutral pose", "Neutral standing state."),
    choice("Seated", "the subject seated with a stable posture", "Seated state."),
    choice("Walking mid-step", "the subject mid-step while moving through the frame", "Locomotion state."),
    choice("Profile turn", "the subject turned in profile toward the side of frame", "Profile/orientation state."),
    choice("Reaching", "the subject reaching toward the nearby object", "Interaction pose."),
    choice("Crouched", "the subject in a low crouched pose", "Low-body pose."),
    choice("Holding object", "the subject holding the primary object in a clearly visible position", "Object-holding state."),
  ]),
  anchorTraits: frozen([
    choice("Viewpoint", "the camera viewpoint and viewing angle", "Anchor camera orientation."),
    choice("Framing", "the shot size and framing", "Anchor shot scale."),
    choice("Subject placement", "subject placement and spacing within the frame", "Anchor composition position."),
    choice("Pose", "the subject's pose and orientation", "Anchor body pose."),
    choice("Object state", "the visible object state and object placement", "Anchor prop/object state."),
    choice("Scene layout", "the scene layout and spatial relationships", "Anchor environment layout."),
    choice("Lighting", "the lighting direction, intensity, and color treatment", "Anchor lighting."),
    choice("Shot order", "shot order and planning structure", "Anchor storyboard order."),
  ]),
  mutableTraits: frozen([
    choice("Action", "the action and motion that occur after the anchored frame", "Allow movement away from the anchor."),
    choice("Background", "the background or surrounding environment", "Allow environment change."),
    choice("Wardrobe / color", "wardrobe details and colors", "Allow clothing/color change."),
    choice("Camera movement", "camera movement after the anchored composition", "Allow camera motion."),
    choice("Lighting", "lighting and time-of-day treatment", "Allow lighting change."),
    choice("Object state", "the state of manipulated objects", "Allow object state change."),
  ]),
  spatialTraits: frozen([
    choice("Viewpoint", "viewpoint and camera orientation", "Preserve view direction."),
    choice("Centered placement", "centered subject placement", "Preserve centered layout."),
    choice("Left/right spacing", "left-right subject spacing and relative placement", "Preserve horizontal relationships."),
    choice("Foreground/background", "foreground-background relationships", "Preserve depth ordering."),
    choice("Subject/object distance", "distance and spacing between the subject and key objects", "Preserve relative distance."),
    choice("Scene depth", "depth layout and major spatial planes", "Preserve scene depth."),
  ]),
  appearanceDetails: frozen([
    choice("Face + hair", "face, hair, and distinctive identity cues", "Primary facial/identity detail."),
    choice("Clothing", "clothing silhouette, fabric, color, and fit", "Wardrobe detail."),
    choice("Accessories", "accessories and worn objects", "Accessory detail."),
    choice("Body proportions", "body proportions, silhouette, and scale", "Proportion detail."),
    choice("Material / texture", "material, texture, and surface finish", "Surface detail."),
    choice("Color", "color palette and color relationships", "Color detail."),
    choice("Distinctive marks", "distinctive marks, patterns, and small identifying details", "Fine identity/detail cues."),
  ]),
  closeupDetails: frozen([
    choice("Face", "facial features, skin detail, and expression", "Face close-up detail."),
    choice("Hands / nails", "hand shape, nail shape, nail color, and nail design", "Hand/nail detail."),
    choice("Fabric", "fabric weave, seams, pattern, and material texture", "Clothing/material detail."),
    choice("Accessory", "accessory shape, material, color, and fine design", "Accessory detail."),
    choice("Object surface", "object surface texture, markings, edges, and material finish", "Object close-up detail."),
    choice("Interface / text", "interface layout, visible labels, icons, and exact text placement", "Interface/text detail."),
  ]),
  framingViewpoint: frozen([
    choice("Medium-wide · eye level", "medium-wide framing from eye level", "Balanced body/environment view."),
    choice("Medium · eye level", "medium framing from eye level", "Neutral conversational framing."),
    choice("Close-up · eye level", "close-up framing from eye level", "Face/detail emphasis."),
    choice("Medium · low angle", "medium framing from a low angle", "Low-angle subject emphasis."),
    choice("Wide · high angle", "wide framing from a high angle", "High-angle scene overview."),
    choice("Medium · over shoulder", "medium over-the-shoulder framing", "Conversation/interaction viewpoint."),
    choice("Medium · profile", "medium profile framing from the subject's side", "Side-view composition."),
  ]),
  openingState: frozen([
    choice("Neutral facing camera", "The subject is stable, facing the camera, and positioned clearly in frame", "Simple opening state."),
    choice("Profile", "The subject begins in profile, oriented toward the side of frame", "Side-facing opening."),
    choice("Seated", "The subject begins seated in a stable posture", "Seated opening."),
    choice("Standing", "The subject begins standing with a balanced neutral posture", "Standing opening."),
    choice("Already moving", "The subject is already in motion at the opening frame", "Open mid-action."),
    choice("Holding object", "The subject begins while visibly holding the key object", "Object-interaction opening."),
  ]),
  actionSequence: frozen([
    choice("Reach → lift → use → settle", "The subject reaches for the object, lifts it, uses it, then settles into the resulting pose", "Complete object-action sequence."),
    choice("Turn → look → react", "The subject turns toward the new focus, looks at it, then visibly reacts", "Orientation/reaction sequence."),
    choice("Enter → cross → stop", "The subject enters the frame, crosses the scene, then stops at the intended position", "Locomotion sequence."),
    choice("Pick up → inspect → place", "The subject picks up the object, inspects it, then places it down", "Manipulation sequence."),
    choice("Crouch → jump → land", "The subject crouches, jumps, follows the airborne motion, then lands and stabilizes", "Athletic motion sequence."),
    choice("Open → interact → close", "The subject opens the object, interacts with its contents, then closes it", "Open/close interaction."),
    choice("Transform → stabilize", "The visible form changes progressively, completes the transformation, then stabilizes", "Transformation sequence."),
  ]),
  transitionChanges: frozen([
    choice("Pose + orientation", "The pose and orientation change progressively while identity remains consistent", "Pose transition."),
    choice("Object state", "The manipulated object's state changes progressively toward the final state", "Object-state transition."),
    choice("Frame position", "The subject moves across the frame toward the final placement", "Position transition."),
    choice("Lighting / time", "Lighting and time-of-day cues change progressively toward the final frame", "Lighting transition."),
    choice("Camera distance / angle", "Camera distance and viewing angle change gradually toward the final composition", "Composition transition."),
    choice("Environment", "The visible environment changes continuously toward the final scene state", "Environment transition."),
    choice("Transformation", "The subject or object transforms continuously toward the final form", "Morph/state transition."),
  ]),
  convergence: frozen([
    choice("Match final pose", "The motion progressively narrows until the final pose and orientation match the supplied final frame", "Converge on pose."),
    choice("Match framing + placement", "Camera framing and subject placement progressively converge on the supplied final composition", "Converge on composition."),
    choice("Match object state", "The manipulated object progressively reaches the exact visible state in the final frame", "Converge on object state."),
    choice("Match lighting + color", "Lighting, color, and visible scene treatment progressively converge on the final frame", "Converge on look."),
    choice("Settle + hold", "Remaining motion decreases as the scene settles into and holds the supplied final state", "Stable landing."),
  ]),
  precedingState: frozen([
    choice("Earlier pose in same scene", "The same scene and subject begin in an earlier compatible pose and position", "Infer a prior body state."),
    choice("Object before final state", "The key object begins in a plausible earlier state before reaching the final configuration", "Infer a prior object state."),
    choice("Subject outside final position", "The subject begins away from the final placement and moves into it", "Infer a prior spatial state."),
    choice("Earlier lighting / time", "The scene begins with an earlier compatible lighting state that can transition into the final frame", "Infer a prior lighting state."),
  ]),
  subjectPose: frozen([
    choice("Centered + front-facing", "centered, front-facing, and clearly visible with a stable upright pose", "Simple identity-forward composition."),
    choice("Rule-of-thirds + three-quarter", "placed on a rule-of-thirds line in a three-quarter orientation", "Natural off-center pose."),
    choice("Profile + side placement", "shown in profile and placed toward the side of frame", "Profile composition."),
    choice("Seated + centered", "seated near the center of frame with a stable posture", "Seated composition."),
    choice("Mid-action", "caught mid-action with the body orientation and frame position clearly readable", "Dynamic pose."),
  ]),
  environment: frozen([
    choice("Indoor · soft practical light", "an indoor room with visible practical fixtures and soft naturalistic lighting", "General interior."),
    choice("Outdoor · daylight", "an outdoor setting in natural daylight with a clearly readable background", "General exterior."),
    choice("Night urban", "an urban night environment with street lighting and visible background depth", "Night city."),
    choice("Overcast exterior", "an overcast exterior with soft diffuse light and restrained shadows", "Soft cloudy daylight."),
    choice("Studio", "a controlled studio environment with clean background separation and deliberate lighting", "Controlled studio."),
    choice("Natural landscape", "a natural outdoor landscape with environmental depth and weather cues", "Nature setting."),
  ]),
  secondaryMotion: frozen([
    choice("Hair / fabric follow-through", "Hair and fabric lag behind the primary movement, then settle naturally", "Secondary cloth/hair inertia."),
    choice("Particles / debris", "The impact or movement sends particles or debris outward before they settle", "Particle response."),
    choice("Water / splash", "Contact and acceleration create water motion, droplets, and delayed splash response", "Liquid response."),
    choice("Dust / smoke", "Movement through the environment disturbs dust or smoke that trails behind", "Atmospheric response."),
    choice("Object inertia", "Changes in acceleration cause nearby loose objects to lag, swing, or slide", "Object inertia."),
    choice("Body recoil", "The force of the action produces visible recoil and recovery through the body", "Physical body response."),
  ]),
  soundEvents: frozen([
    choice("Footsteps", "footsteps synchronized to the subject's movement", "Locomotion sound."),
    choice("Impact", "a clear impact synchronized to the visible contact", "Impact sound."),
    choice("Door / mechanism", "the click, scrape, or mechanism sound of the object moving", "Mechanical/object sound."),
    choice("Fabric", "fabric rustle synchronized to body movement", "Clothing sound."),
    choice("Wind / rain", "wind or rain audible in the scene", "Weather sound."),
    choice("Vehicle / machine", "the relevant vehicle or machine sound synchronized to its operation", "Machine sound."),
    choice("Breathing", "breathing or exertion synchronized to the performance", "Human non-verbal sound."),
  ]),
  audioEvent: frozen([
    choice("Footsteps", "Footsteps synchronize to the subject's movement", "Complete audible event sentence."),
    choice("Impact", "A clear impact sounds at the visible point of contact", "Complete impact event sentence."),
    choice("Door / mechanism", "The moving object produces a synchronized click, scrape, or mechanism sound", "Complete mechanical/object event sentence."),
    choice("Fabric", "Fabric rustle synchronizes to the body movement", "Complete clothing-sound event sentence."),
    choice("Wind / rain", "Wind or rain is audible in the scene", "Complete weather-sound event sentence."),
    choice("Vehicle / machine", "The relevant vehicle or machine sound synchronizes to its visible operation", "Complete machine event sentence."),
    choice("Breathing", "Breathing or exertion synchronizes to the performance", "Complete non-verbal human event sentence."),
  ]),
  timedSoundEvent: frozen([
    choice("Footsteps", "footsteps synchronize to the subject's movement", "Clause for a within-shot timestamp."),
    choice("Impact", "a clear impact sounds at the visible point of contact", "Clause for a within-shot timestamp."),
    choice("Door / mechanism", "the moving object produces a synchronized click, scrape, or mechanism sound", "Clause for a within-shot timestamp."),
    choice("Fabric", "fabric rustle synchronizes to the body movement", "Clause for a within-shot timestamp."),
    choice("Wind / rain", "wind or rain becomes audible in the scene", "Clause for a within-shot timestamp."),
    choice("Vehicle / machine", "the relevant vehicle or machine sound synchronizes to its visible operation", "Clause for a within-shot timestamp."),
    choice("Breathing", "breathing or exertion becomes audible with the performance", "Clause for a within-shot timestamp."),
  ]),
  diegeticMusic: frozen([
    choice("Radio", "Music plays from a radio in the scene and remains spatially localized to it", "Diegetic radio music."),
    choice("Phone", "Music plays from a phone speaker in the scene", "Diegetic phone music."),
    choice("Television", "Music is audible from a television in the scene", "Diegetic TV music."),
    choice("Live instrument", "A visible instrument is performed in the scene, with its sound synchronized to the performance", "Live diegetic performance."),
    choice("Speaker system", "Music plays from a visible or implied in-scene speaker system", "Environmental diegetic music."),
    choice("Band / ensemble", "A visible band or ensemble performs in the scene", "Live group performance."),
  ]),
  pauseDuration: frozen([
    choice("Brief pause", "A brief pause follows", "Short natural pause."),
    choice("0.25 s", "The audio falls silent for 0.25 seconds", "Quarter-second silence."),
    choice("0.5 s", "The audio falls silent for 0.5 seconds", "Half-second silence."),
    choice("1 s", "The audio falls silent for 1 second", "One-second silence."),
    choice("2 s", "The audio falls silent for 2 seconds", "Two-second silence."),
  ]),
  ambience: frozen([
    choice("Room tone", "steady indoor room tone", "Persistent indoor ambience."),
    choice("Wind", "steady wind", "Wind ambience."),
    choice("Rain", "steady rain", "Rain ambience."),
    choice("Traffic", "distant traffic", "Urban traffic bed."),
    choice("Crowd murmur", "low crowd murmur", "Crowd/background voices without intelligible dialogue."),
    choice("Ventilation / hum", "low ventilation and electrical hum", "Mechanical indoor bed."),
    choice("Nature", "birds, insects, leaves, and distant natural ambience", "Natural outdoor bed."),
    choice("Machinery", "continuous low machinery ambience", "Industrial/mechanical bed."),
  ]),
  foley: frozen([
    choice("Footsteps", "footsteps", "Movement foley."),
    choice("Fabric movement", "fabric rustle and clothing movement", "Clothing foley."),
    choice("Object handling", "hand contact and object-handling sounds", "Object interaction foley."),
    choice("Impacts", "impacts and contact sounds", "Impact foley."),
    choice("Door / mechanism", "door, latch, hinge, and mechanism sounds", "Mechanical foley."),
    choice("Paper", "paper folds, rustles, and creases", "Paper foley."),
    choice("Glass / metal", "glass or metal contact, clinks, and scrapes", "Hard-surface foley."),
    choice("Water", "water movement, drips, splashes, and pours", "Liquid foley."),
  ]),
  nonverbalHuman: frozen([
    choice("Breathing", "breathing", "Normal breath sounds."),
    choice("Panting", "panting", "Heavy breathing/exertion."),
    choice("Laughter", "laughter", "Non-verbal laugh."),
    choice("Gasp", "a gasp", "Short startled breath."),
    choice("Sigh", "a sigh", "Audible exhale."),
    choice("Exertion", "non-verbal exertion sounds", "Effort/grunts without words."),
    choice("Sobbing", "non-verbal sobbing", "Crying without spoken words."),
    choice("Cough", "a cough", "Coughing sound."),
  ]),
  instruments: frozen([
    choice("Solo piano", "solo piano", "Single piano source."),
    choice("Piano + cello", "piano with sustained cello", "Sparse piano/cello combination."),
    choice("Acoustic guitar + upright bass", "acoustic guitar with sparse upright-bass notes", "Acoustic duo."),
    choice("String ensemble", "a small string ensemble", "String-based score."),
    choice("Synth pads + pulse", "soft synthesizer pads with a restrained electronic pulse", "Electronic texture."),
    choice("Percussion + bass", "tight percussion with a low bass layer", "Rhythm-forward score."),
    choice("Strings + brass", "orchestral strings with restrained brass", "Broader orchestral palette."),
    choice("Ambient texture", "tonal ambient textures without a prominent lead instrument", "Texture-led score."),
  ]),
  tempoRhythm: frozen([
    choice("Slow + sustained", "a slow tempo with sustained tones and little rhythmic activity", "Slow sustained score."),
    choice("Slow + sparse", "a slow tempo with widely spaced notes", "Sparse slow score."),
    choice("Moderate + steady", "a moderate tempo with a steady regular pulse", "Balanced pacing."),
    choice("Moderate + syncopated", "a moderate tempo with a syncopated rhythm", "Off-beat rhythmic movement."),
    choice("Fast + driving", "a fast tempo with a driving repeated pulse", "Fast rhythmic score."),
    choice("Free / rubato", "free timing without a strict pulse", "Flexible timing."),
    choice("Drone / no pulse", "sustained tones with no clear rhythmic pulse", "Non-rhythmic score."),
  ]),
  musicalPattern: frozen([
    choice("Sparse repeated notes", "sparse repeated notes with space between phrases", "Minimal repeated-note pattern."),
    choice("Steady ostinato", "a steady repeating ostinato", "Repeated rhythmic figure."),
    choice("Arpeggio", "a repeating arpeggiated pattern", "Broken-chord pattern."),
    choice("Sustained chords", "long sustained chords", "Held harmonic bed."),
    choice("Pulsing beat", "a regular pulsing beat", "Pulse-led pattern."),
    choice("Rhythmic strumming", "a repeating rhythmic strumming pattern", "Guitar/strummed pattern."),
    choice("Long drones", "long overlapping drones", "Texture-led sustained pattern."),
  ]),
  dynamicChange: frozen([
    choice("Gradual build", "gradually increases in volume and density", "Progressive build."),
    choice("Gradual fade", "gradually decreases in volume and density", "Progressive fade."),
    choice("Stable / no swell", "holds a stable volume and density with no major swell", "Keep dynamics restrained."),
    choice("Sparse → dense", "starts sparse and gradually adds layers", "Increase arrangement density."),
    choice("Dense → sparse", "starts layered and gradually removes elements", "Reduce arrangement density."),
    choice("Brief swell → settle", "briefly swells, then returns to a restrained level", "One controlled swell."),
    choice("Hard stop", "stops abruptly at the intended endpoint", "Abrupt ending."),
  ]),
  speakerIdentity: frozen([
    choice("Woman", "the woman", "Generic visible speaker identity."),
    choice("Man", "the man", "Generic visible speaker identity."),
    choice("Child", "the child", "Generic child speaker identity."),
    choice("Narrator", "the narrator", "Narration source not otherwise identified."),
    choice("Off-screen narrator", "the off-screen narrator", "Voice source that is not visible on screen."),
    choice("Visible character", "the visible character", "Generic on-screen character identity."),
    choice("Singer", "the singer", "Generic singing source."),
  ]),
  voiceTraits: frozen([
    choice("Quiet + breathy", "a quiet, breathy voice", "Voice trait combination used in MiniMax's guide example."),
    choice("Calm + slightly raspy", "a calm, slightly raspy voice", "Voice trait combination used in MiniMax's guide example."),
    choice("Low + resonant + measured", "a low, resonant voice with measured delivery", "Low-pitched measured delivery."),
    choice("High + clear + quick", "a high, clear voice with quick delivery", "Higher-pitched fast delivery."),
    choice("Warm + soft + slow", "a warm, soft voice with slow delivery", "Soft warm delivery."),
    choice("Bright + energetic", "a bright, energetic voice with fast delivery", "Energetic delivery."),
    choice("Whispered", "a quiet whispered voice", "Whisper-like delivery."),
    choice("Neutral + clear", "a neutral, clear voice at a moderate speaking rate", "Neutral default-like delivery."),
  ]),
  speakerCombined: frozen([
    choice("Woman · quiet/breathy", "the woman with a quiet, breathy voice", "Combined identity + voice starter."),
    choice("Man · calm/raspy", "the man with a calm, slightly raspy voice", "Combined identity + voice starter."),
    choice("Narrator · low/measured", "the narrator with a low, resonant voice and measured delivery", "Combined narrator starter."),
    choice("Off-screen narrator · warm/soft", "the off-screen narrator with a warm, soft voice and slow delivery", "Combined off-screen voice starter."),
    choice("Singer · clear", "the singer with a clear, controlled voice", "Combined singing-source starter."),
  ]),
  shotSize: frozen([
    // Insert the framing term only. Host scaffolds say "uses ... framing",
    // avoiding brittle a/an handling such as "A extreme close-up shot".
    choice("Extreme close-up", "extreme close-up", "Very tight detail framing."),
    choice("Close-up", "close-up", "Face/object detail framing."),
    choice("Medium close-up", "medium close-up", "Head/upper-torso emphasis."),
    choice("Medium", "medium", "Balanced subject framing."),
    choice("Medium-wide", "medium-wide", "More body/environment context."),
    choice("Full shot", "full-shot", "Entire subject visible; works for people, animals, and objects."),
    choice("Full-body (person / character)", "full-body", "Entire human/character body visible."),
    choice("Wide", "wide", "Environment and subject visible together."),
    choice("Extreme wide", "extreme-wide", "Environment-dominant framing."),
  ]),
  viewpoint: frozen([
    choice("Eye level", "eye level", "Neutral camera height."),
    choice("Low angle", "a low angle", "Camera looks upward."),
    choice("High angle", "a high angle", "Camera looks downward."),
    choice("Overhead", "directly overhead", "Top-down viewpoint."),
    choice("Ground level", "ground level", "Very low camera placement."),
    choice("Front-facing", "a front-facing viewpoint", "Camera faces subject directly."),
    choice("Three-quarter", "a three-quarter viewpoint", "Oblique front/side view."),
    choice("Profile / side", "the subject's side", "Profile viewpoint."),
    choice("Rear", "behind the subject", "Rear viewpoint."),
    choice("Over-the-shoulder", "an over-the-shoulder position", "View past a foreground subject."),
  ]),
  subjectScene: frozen([
    // These are real noun phrases, not category labels copied into the prompt.
    // They must read naturally after verbs such as "frames", "shows", and
    // "cuts to". Custom remains the default when the actual subject is known.
    choice("Person · generic", "a person", "Generic human subject when no more specific description is intended."),
    choice("Woman", "a woman", "Adult woman as the visible subject."),
    choice("Man", "a man", "Adult man as the visible subject."),
    choice("Child", "a child", "Child as the visible subject."),
    choice("Fictional character", "a fictional character", "Non-specific fictional or stylized character."),
    choice("Animal", "an animal", "Animal subject without inventing species or appearance."),
    choice("Object / prop", "the primary object or prop", "Object- or prop-led framing."),
    choice("Scene / environment", "the surrounding environment", "Environment-led framing."),
    choice("Multiple subjects", "the group of primary subjects", "Multi-subject framing without inventing a count or interaction."),
    choice("Subject + environment", "the primary subject together with the surrounding environment", "Balanced subject/environment framing."),
  ]),
  physicalCause: frozen([
    choice("Acceleration / stop", "a sudden acceleration or stop", "Inertial secondary motion."),
    choice("Impact", "the visible impact", "Contact-driven response."),
    choice("Gravity / fall", "gravity during the fall", "Gravity-driven motion."),
    choice("Wind", "wind moving through the scene", "Wind-driven secondary motion."),
    choice("Contact / push", "direct contact or pushing force", "Contact-driven motion."),
    choice("Rotation", "the subject or object's rotation", "Rotational inertia."),
    choice("Running / locomotion", "the subject's locomotion and changing momentum", "Body-motion cause."),
  ]),
  newShot: frozen([
    choice("Close detail", "a close detail of the key object or body action", "Cut to detail."),
    choice("Reverse angle", "the reverse angle on the same interaction", "Cut across the interaction."),
    choice("Wider establishing view", "a wider establishing view of the same scene", "Reveal more space."),
    choice("Reaction", "the subject's reaction from a new viewpoint", "Reaction shot."),
    choice("Object result", "the resulting object state in a tighter view", "Result/detail shot."),
    choice("New location", "the next location or environment", "Cut to a different setting."),
  ]),
  newShotViewpoint: frozen([
    choice("Eye-level view", "an eye-level view of the current subject or scene", "New shot with an explicit neutral viewpoint."),
    choice("Low-angle view", "a low-angle view of the current subject or scene", "New shot from below."),
    choice("High-angle view", "a high-angle view of the current subject or scene", "New shot from above."),
    choice("Overhead view", "an overhead view of the current subject or scene", "New top-down shot."),
    choice("Ground-level view", "a ground-level view of the current subject or scene", "New very-low camera view."),
    choice("Front-facing view", "a front-facing view of the current subject", "New frontal shot."),
    choice("Three-quarter view", "a three-quarter view of the current subject", "New oblique frontal shot."),
    choice("Profile view", "a profile view of the current subject", "New side shot."),
    choice("Rear view", "a rear view of the current subject", "New shot from behind."),
    choice("Over-the-shoulder view", "an over-the-shoulder view of the current interaction", "New OTS shot."),
  ]),
  fadeDestination: frozen([
    choice("Black", "black", "Fade to black."),
    choice("White", "white", "Fade to white."),
    choice("New scene", "the next scene", "Fade into a new scene."),
    choice("Darkness", "a darkened version of the current scene", "Fade scene lighting down."),
    choice("Bright wash", "a bright washed-out frame", "Fade scene lighting up."),
  ]),
});

export const PLACEHOLDER_PRESET_GROUPS = Object.freeze({
  "identity / appearance / structure to keep": ["retainedTraits"],
  "features retained": ["retainedTraits"],
  "features changed": ["changedTraits"],
  "attributes": ["attributeTransfer"],
  "target subject": ["subjectScene"],
  "style / category / composition / atmosphere": ["weakVisual"],
  "copied segment / layers": ["audioSegments"],
  "what is added / removed / replaced": ["audioEdits"],
  "timbre / rhythm / music style / dialogue content / sound texture": ["audioProperties"],
  "audio category / atmosphere": ["audioCategory"],
  "tracked subject": ["trackedSubject"],
  "subject": ["subjectScene"],
  "setup / anticipation": ["actionStage"],
  "main action / transition": ["actionStage"],
  "completion / landing": ["completionStage"],
  "timing / body mechanics / trajectory": ["motionQualities"],
  "action / motion performance": ["motionPerformance"],
  "action / motion pattern": ["motionPattern"],
  "pose sequence / timing / body mechanics": ["motionMechanics"],
  "source contribution": ["sourceContribution"],
  "overall action / premise": ["premise"],
  "high-level shot progression": ["shotProgression"],
  "visual style": ["visualStyle"],
  "lighting / color / material traits": ["styleTraits"],
  "subject / scene / composition": ["composition", "subjectScene"],
  "pose / composition / state": ["poseState", "composition"],
  "final pose / state / composition": ["poseState", "composition"],
  "what the picture anchors": ["anchorTraits"],
  "what may change": ["mutableTraits"],
  "viewpoint / placement / spatial relationships": ["spatialTraits"],
  "overall appearance details": ["appearanceDetails"],
  "close-up detail": ["closeupDetails"],
  "framing and viewpoint": ["framingViewpoint"],
  "opening subject state": ["openingState"],
  "action in playback order": ["actionSequence"],
  "first-frame visible state": ["openingState"],
  "changes between first and last frame": ["transitionChanges"],
  "approach to final frame": ["convergence"],
  "state before the final frame": ["precedingState"],
  "motion toward the final frame": ["transitionChanges"],
  "final-frame convergence": ["convergence"],
  "subject appearance / pose / frame position": ["subjectPose"],
  "environment / lighting": ["environment"],
  "secondary motion / physical response": ["secondaryMotion"],
  "target video + main reference relationships": ["summaryRelationships"],
  "audio event / timing": ["audioEvent"],
  "diegetic music source / performance": ["diegeticMusic"],
  "pause / silence duration": ["pauseDuration"],
  "ambient sources": ["ambience"],
  "foley / impacts / object sounds": ["foley"],
  "breathing / exertion / laughter / other": ["nonverbalHuman"],
  "instruments / sound sources": ["instruments"],
  "tempo / rhythm": ["tempoRhythm"],
  "musical pattern": ["musicalPattern"],
  "dynamic change": ["dynamicChange"],
  "speaker identity": ["speakerIdentity"],
  "voice traits": ["voiceTraits"],
  "speaker identity / voice traits": ["speakerCombined"],
  "target speaker description": ["speakerCombined"],
  "shot size / framing": ["shotSize"],
  "viewpoint": ["viewpoint"],
  "subject / scene": ["subjectScene"],
  "appearance / pose / orientation / frame position": ["subjectPose"],
  "location / background / lighting / weather": ["environment"],
  "visible action stages / state changes": ["actionSequence"],
  "physical cause / movement": ["physicalCause"],
  "diegetic sounds": ["soundEvents"],
  "visual style + opening composition": ["styleComposition"],
  "event within the current shot": ["timedActionStage", "timedSoundEvent"],
  "new shot content / viewpoint": ["newShot", "newShotViewpoint"],
  "cross-dissolve destination": ["newShot", "subjectScene"],
  "fade destination": ["fadeDestination"],
  "wipe destination": ["newShot", "subjectScene"],
  "action onset": ["actionStage"],
  "continuous development": ["actionSequence"],
  "result / reaction": ["completionStage"],
  "first-frame state": ["openingState"],
  "intermediate changes": ["transitionChanges"],
  "narrowing differences": ["convergence"],
  "plausible preceding state": ["precedingState"],
  "action / transition path": ["transitionChanges"],
  "gradual convergence": ["convergence"],
});

export function presetChoicesForPlaceholder(key) {
  const groupNames = PLACEHOLDER_PRESET_GROUPS[String(key || "")] || [];
  const seen = new Set();
  const out = [];
  for (const groupName of groupNames) {
    const choices = PROMPT_CHOICE_GROUPS[groupName] || [];
    for (const item of choices) {
      const id = `${item.label}\u001f${item.insertText}`;
      if (seen.has(id)) continue;
      seen.add(id);
      out.push({ ...item, group: groupName });
    }
  }
  return out;
}
